### ISSUE TITLE
Erro ao instalar pacote

### ISSUE THREAD

**Issue by massonetto** [pablosanches/registrobr-epp#1]
Estou tentando instalar o pacote, mas estou com o seguinte erro:

**[InvalidArgumentException]                                                                                                                                                 
  Could not find a matching version of package pablosanches/registrobr-epp. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).**

Não sou familarizado com o PHP, poderia me ajudar se estou fazendo algo errado, ou seria um problema do pacote mesmo?

Obrigado

**Comment by pablosanches** [comment]
Opa, muito obrigado pelo contato amigo!
Faltou eu submeter o pacote no packagist, por isso você recebeu este erro.
Pode rodar o `composer require pablosanches/registrobr-epp` no seu projeto que você vai conseguir instalar o pacote!

Se puder, me deixa um feedback se funcionou para eu fechar a issue. Obrigado e abraços!!!

**Comment by massonetto** [comment]
Muito obrigado parceiro pela rapida solução, deu certo agora.

Obrigado também por disponibilizar o pacote. 

Abraços

**Comment by pablosanches** [comment]
Fico feliz que deu certo!! Qualquer dúvida ai me coloco a disposição!!!

Vlwww!!
Abraços.
